# ABC config for mm10 BAP1-KO cerebellum analysis
# Modified from default hg38 config

### INPUT DATA
biosamplesTable: "config/config-biosamples-mm10.tsv"

### OUTPUT DATA
results_dir: "results/"

### REFERENCE FILES
ref:
        chrom_sizes: "/expanse/lustre/projects/csd940/zalibhai/taiji-new/reference/mm10/mm10.chrom.sizes"
        regions_blocklist: "/expanse/lustre/projects/csd940/zalibhai/abc/reference/mm10_merged_blacklist.bed"
        ubiquitous_genes: "/expanse/lustre/projects/csd940/zalibhai/abc/reference/mm10_ubiquitous_genes.tsv"
        genes: "/expanse/lustre/projects/csd940/zalibhai/abc/reference/mm10_genes.bed"
        genome_tss: "/expanse/lustre/projects/csd940/zalibhai/abc/reference/mm10_tss.bed"
        qnorm: "reference/EnhancersQNormRef.K562.txt"
        abc_thresholds: "reference/abc_thresholds.tsv"

### RULE SPECIFIC PARAMS
params_macs:
        pval: 0.1
        genome_size: mm
        threads: 10

params_candidate:
        peakExtendFromSummit: 250
        nStrongestPeaks: 150000

params_neighborhoods:
        use_qnorm: False

params_predict:
        flags: "--scale_hic_using_powerlaw"
        hic_gamma: 1.024238616787792
        hic_scale: 5.9594510043736655
        hic_pseudocount_distance: 5000

params_filter_predictions:
        score_column: "ABC.Score"
        threshold: 0.02
        include_self_promoter: True
        only_expressed_genes: False

### INTERNAL USE ONLY
ABC_DIR_PATH: ""
