# biomodal/downstream/scripts/viz_sections/section_09_summary.R
# Section 9: Summary Statistics
# Standalone script - sources shared config for all dependencies and data
# NOTE: This section depends on the 'coordinated' data frame from Section 5.
# The coordinated analysis is re-computed here so this script is self-contained.

# Run from downstream/ directory
source("scripts/viz_sections/_shared_config.R")

# =============================================================================
# Re-compute coordinated changes (from Section 5) for summary
# =============================================================================

mc_sig <- mc_dmr %>%
  dplyr::filter(significant) %>%
  dplyr::select(gene, mc_diff = mod_difference, mc_q = dmr_qvalue,
                mc_ctrl = mean_mod_group1, mc_mut = mean_mod_group2)

hmc_sig <- hmc_dmr %>%
  dplyr::filter(significant) %>%
  dplyr::select(gene, hmc_diff = mod_difference, hmc_q = dmr_qvalue,
                hmc_ctrl = mean_mod_group1, hmc_mut = mean_mod_group2)

coordinated <- inner_join(mc_sig, hmc_sig, by = "gene")

coordinated <- coordinated %>%
  mutate(
    coordinated_pattern = (mc_diff > 0 & hmc_diff < 0),
    combined_effect = abs(mc_diff) + abs(hmc_diff)
  ) %>%
  arrange(desc(combined_effect))

# =============================================================================
# SECTION 9: SUMMARY STATISTICS
# =============================================================================

cat("================================================================================\n")
cat("SECTION 9: SUMMARY STATISTICS\n")
cat("================================================================================\n\n")

# Generate summary statistics
summary_text <- sprintf("
================================================================================
BIOMODAL DUET evoC DIFFERENTIAL METHYLATION ANALYSIS SUMMARY
================================================================================

Analysis Date: %s
Genome: GRCm38 (mm10)
Comparison: BAP1-KO Mutant vs Wildtype Control
Samples: 4 (2 Control, 2 Mutant)

--------------------------------------------------------------------------------
DIFFERENTIAL METHYLATION STATISTICS (CG Context, Gene Bodies)
--------------------------------------------------------------------------------

5mC (5-methylcytosine):
  Total genes tested: %d
  Significant (q < %.2f): %d (%.1f%%)
  Hypermethylated: %d
  Hypomethylated: %d
  Mean change (significant): %+.2f%%

5hmC (5-hydroxymethylcytosine):
  Total genes tested: %d
  Significant (q < %.2f): %d (%.1f%%)
  Increased: %d
  Decreased: %d
  Mean change (significant): %+.2f%%

--------------------------------------------------------------------------------
COORDINATED CHANGES
--------------------------------------------------------------------------------

Genes significant in both mC and hmC: %d
Genes with mC\u2191 / hmC\u2193 pattern: %d (%.1f%%)

This pattern indicates impaired TET-mediated active demethylation:
  5mC \u2192 (TET1/2/3) \u2192 5hmC \u2192 5fC \u2192 5caC \u2192 C (unmethylated)

BAP1 loss \u2192 Increased H2AK119ub \u2192 Altered chromatin \u2192 TET access restricted

--------------------------------------------------------------------------------
TOP AFFECTED GENES (Coordinated Pattern)
--------------------------------------------------------------------------------

Gene      mC Change    hmC Change   mC q-value     hmC q-value
----      ---------    ----------   ----------     -----------
%s

--------------------------------------------------------------------------------
KEY FINDINGS
--------------------------------------------------------------------------------

1. PRIMARY AFFECTED REGIONS: Gene bodies (NOT promoters or CpG islands)
2. COORDINATED PATTERN: 5mC increase + 5hmC decrease at same loci
3. NEURONAL GENES: Top hits include synaptic/neuronal genes (Syt1, Cntnap2, Dlgap1)
4. NON-CpG: No significant changes in CHG/CHH contexts
5. MECHANISM: Consistent with blocked TET-mediated active demethylation

--------------------------------------------------------------------------------
OUTPUT FILES
--------------------------------------------------------------------------------

Plots: %s
Tables: %s

Generated by: biomodal_visualizations.R
================================================================================
",
  format(Sys.time(), "%Y-%m-%d %H:%M:%S"),
  nrow(mc_dmr), Q_THRESHOLD, sum(mc_dmr$significant),
  100 * sum(mc_dmr$significant) / nrow(mc_dmr),
  sum(mc_dmr$significant & mc_dmr$mod_difference > 0),
  sum(mc_dmr$significant & mc_dmr$mod_difference < 0),
  mean(mc_dmr$mod_difference[mc_dmr$significant]) * 100,
  nrow(hmc_dmr), Q_THRESHOLD, sum(hmc_dmr$significant),
  100 * sum(hmc_dmr$significant) / nrow(hmc_dmr),
  sum(hmc_dmr$significant & hmc_dmr$mod_difference > 0),
  sum(hmc_dmr$significant & hmc_dmr$mod_difference < 0),
  mean(hmc_dmr$mod_difference[hmc_dmr$significant]) * 100,
  nrow(coordinated),
  sum(coordinated$coordinated_pattern),
  100 * mean(coordinated$coordinated_pattern),
  paste(sprintf("%-10s %+8.1f%%    %+9.1f%%   %.1e    %.1e",
                head(coordinated$gene[coordinated$coordinated_pattern], 7),
                head(coordinated$mc_diff[coordinated$coordinated_pattern], 7) * 100,
                head(coordinated$hmc_diff[coordinated$coordinated_pattern], 7) * 100,
                head(coordinated$mc_q[coordinated$coordinated_pattern], 7),
                head(coordinated$hmc_q[coordinated$coordinated_pattern], 7)),
        collapse = "\n"),
  OUTPUT_DIR,
  TABLES_DIR
)

# Write summary file
writeLines(summary_text, file.path(TABLES_DIR, "summary_statistics.txt"))
cat("Saved summary_statistics.txt\n")

# Print summary
cat(summary_text)

cat("Section 9 complete.\n\n")
