# config/edgeR_config.yaml
# Configuration for Mariner differential loop analysis with edgeR

## Input/Output Paths
paths:
  base_dir: "/expanse/lustre/projects/csd940/zalibhai/mariner"
  
  # Input files from Mariner pipeline
  input:
    counts_matrix: "outputs/full/06_counts_matrix.rds"
    coordinates: "outputs/full/03_binned.rds"
    merged_loops: "outputs/full/02_merged.rds"
    qc_summary: "outputs/qc_report/qc_report_summary.rds"
  
  # Hiccups comparison files
  hiccups:
    ctrl_enriched: "/expanse/lustre/projects/csd940/ctea/nf-hic/juicerpre/merged/diffhiccups_results/resorted_ctrl_vs_resorted_mut/file1/postprocessed_pixels_5000.bedpe"
    mut_enriched: "/expanse/lustre/projects/csd940/ctea/nf-hic/juicerpre/merged/diffhiccups_results/resorted_ctrl_vs_resorted_mut/file2/postprocessed_pixels_5000.bedpe"
  
  # Output directories
  output:
    base: "outputs/edgeR_results"
    primary: "outputs/edgeR_results/primary_analysis"
    comparison: "outputs/edgeR_results/hiccups_comparison"
    plots: "outputs/edgeR_results/plots"
    logs: "outputs/edgeR_results/logs"

## Sample Information
samples:
  names: ["ctrl_M1", "ctrl_M2", "ctrl_M3", "mut_M1", "mut_M2", "mut_M3"]
  groups: ["ctrl", "ctrl", "ctrl", "mut", "mut", "mut"]
  group_labels: ["Control", "Mutant"]
  description: "BAP1 mutant vs control Hi-C with biological replicates (n=3 per condition)"

## Statistical Parameters
statistics:
  # Dispersion estimation (data-driven from replicates)
  # No fixed BCV - will be estimated using estimateDisp()
  # Expected BCV for controlled Hi-C: 0.1-0.3
  estimate_method: "robust"  # Use robust estimation for dispersions

  # Filtering thresholds
  filtering:
    min_count: 5         # Minimum count threshold
    min_total_count: 15  # Minimum total across samples (can be stricter with replicates)
    min_prop: 0.5        # At least half the samples in smallest group (2/3 for n=3)
  
  # Significance thresholds
  fdr_primary: 0.05      # Primary FDR cutoff
  fdr_exploratory: 0.10  # Exploratory threshold for sensitivity
  
  # Effect size categories
  fold_change_thresholds:
    strong: 1.0          # |logFC| > 1 (2-fold)
    moderate: 0.5        # |logFC| > 0.5 (1.4-fold)
    weak: 0.0            # Any significant change
  
  # Normalization
  normalization_method: "TMM"  # Trimmed Mean of M-values

## Comparison Settings
comparison:
  # Hiccups matching parameters
  match_radius_kb: 10    # 10kb tolerance (matches Mariner merge radius)
  require_both_anchors: true
  
  # Overlap categories
  categories:
    - "shared_concordant"     # Both methods, same direction
    - "shared_discordant"     # Both methods, opposite direction
    - "mariner_specific"      # Only Mariner significant
    - "hiccups_specific"      # Only Hiccups significant
    - "non_differential"      # Neither method significant

## Replicate Quality Control
replicate_qc:
  min_within_group_correlation: 0.90  # Flag if within-group correlation < 0.90
  max_outlier_distance: 2.5           # MDS distance threshold for outliers
  lib_size_fold_threshold: 2.0        # Flag if replicate differs >2-fold from median

## Visualization Settings
visualization:
  # Sample QC plots
  mds_plot:
    dimensions: [[1,2], [2,3]]  # Multiple MDS views
    color_by_group: true
    label_samples: true

  bcv_plot:
    show_trend: true
    show_common: true

  ql_dispersion_plot:
    show_shrinkage: true

  # Differential results plots
  ma_plot:
    point_size: 0.8
    alpha: 0.6
    fdr_threshold: 0.05
    fc_lines: [-1, 1]    # ±2-fold change reference lines

  volcano_plot:
    point_size: 0.8
    alpha: 0.6
    fdr_threshold: 0.05
    fc_threshold: 1.0
    label_top_n: 20      # Label top N significant loops
  
  # Color schemes
  colors:
    significant_up: "#d73027"      # Red for up in mutant
    significant_down: "#4575b4"    # Blue for down in mutant
    non_significant: "#999999"     # Gray for NS
    shifted_loops: "#fdae61"       # Orange for positionally shifted
    hiccups_overlap: "#1b7837"     # Green for Hiccups agreement
  
  # Output formats
  output_formats: ["pdf", "png"]
  dpi: 300
  width: 8
  height: 6

## Quality Control
qc:
  # Thresholds for warnings
  min_library_size: 5e6        # Per-replicate minimum (lower than merged)
  max_bcv: 0.5                 # Warn if common BCV exceeds 0.5 (high for controlled)
  min_filtered_loops: 10000    # Expect at least this many after filtering
  min_residual_df: 3           # Minimum residual df (should be 4 for 6 samples, 2 groups)

  # Replicate quality
  min_within_correlation: 0.90 # Flag low within-group correlation

  # Shifted loop analysis
  track_positional_shifts: true
  shift_enrichment_test: true

## Output Specifications
outputs:
  # File formats and naming
  results_formats:
    primary: ["tsv", "rds"]
    annotated: ["tsv", "xlsx"]
  
  # Results tables to generate
  tables:
    - name: "all_results"
      description: "Complete results for all tested loops"
      include_columns: ["loop_id", "chr1", "start1", "end1", "chr2", "start2", "end2", 
                       "logFC", "logCPM", "PValue", "FDR", "significant", "category", "shift_status"]
    
    - name: "significant_loops"
      description: "FDR < 0.05 loops only"
      filter: "FDR < 0.05"
    
    - name: "top_differential"
      description: "Top 100 by effect size"
      sort_by: "abs(logFC)"
      top_n: 100
  
  # Summary statistics to compute
  summary_stats:
    - "total_loops_tested"
    - "significant_loops_fdr05"
    - "significant_loops_fdr10"
    - "loops_up_in_mutant"
    - "loops_down_in_mutant"
    - "median_abs_logfc"
    - "strong_differential_count"
    - "moderate_differential_count"
    - "shifted_loops_tested"
    - "shifted_loops_significant"

## Runtime Configuration
runtime:
  parallel_cores: 8      # Matches SLURM --cpus-per-task
  memory_limit_gb: 32    # Matches SLURM --mem
  seed: 42              # For reproducibility
  verbose: true
  progress_updates: true

## Validation Checks
validation:
  # Pre-analysis checks
  check_input_files: true
  verify_coordinates: true
  check_count_integrity: true
  
  # Post-analysis checks
  verify_output_files: true
  check_result_validity: true
  generate_qc_report: true

## Metadata
metadata:
  pipeline_version: "2.0.0"
  edgeR_version: "4.x"
  analysis_date: "2025-10-20"
  analyst: "Zaki"
  project: "BAP1_mutant_Hi-C_differential_loops"
  description: |
    Replicate-aware differential chromatin loop analysis using Mariner buffer aggregation
    with edgeR quasi-likelihood GLM testing. Uses biological replicates (n=3 per condition)
    for proper variance estimation and improved statistical power.
  improvements_over_v1:
    - "Biological replicates enable data-driven dispersion estimation"
    - "Quasi-likelihood F-tests with proper error rate control"
    - "MDS and BCV plots for quality control"
    - "Robust estimation to handle outliers"
    - "Expected >100× improvement in differential loop detection"
