# APA launcher for SE-DEG contact frequency analysis
# Run on HPC (requires .hic files and mariner::pullHicMatrices)
#
# Template based on scripts/apa_analysis.R
# Input BEDPEs generated by se_deg_proximity.R
#
# Generated: 2026-05-08 15:50:11.437641

# TODO: adapt apa_analysis.R to load these BEDPEs as GInteractions
# and run pullHicMatrices + APA aggregation per gene class
